Fix lowercase conversion
xvoland/Extract pull request #22
Opened 2020-08-22 23:12 UTC by druckdev

Convert to lowercase instead of removing a trailing comma.
This reverts https://github.com/xvoland/Extract/commit/60f9ac56f774d9db04e8989e35a881c700ec96a9.

2020-11-06 12:49 UTC, xvoland commented
`${n,,}: bad substitution`

2020-11-06 12:50 UTC, xvoland requested changes
${n,,}: bad substitution

2020-11-06 12:51 UTC, xvoland commented
Anyway, I don't think it is necessary to force the conversion to lowercase

2020-11-06 12:51 UTC, closed without merging

2020-11-09 20:22 UTC, druckdev commented
May I ask, what bash version you are running?


Would you please look at the discussion below https://github.com/xvoland/Extract/commit/60f9ac56f774d9db04e8989e35a881c700ec96a9 again? You seem to be aware of the error yourself.

As it is right now, the script removes a trailing comma, since `${parameter%word}` removes a matching suffix pattern. The `${parameter,,}` expansion builtin of bash is the short form of `${parameter,,?}` and it modifies the case of every alphabetic character in `parameter` to be lowercase. This conversion **does** make sense if the script is meant to work case-insensitive. I guessed that you want that too, since you merged https://github.com/xvoland/Extract/pull/4/ that introduced this in the first place.

If you do not want to use the bash builtin, I would kindly ask you to at least use the `awk` version of https://github.com/xvoland/Extract/pull/4/. But as it is right now it makes absolutely no sense.
If you do that, there would be no point in not merging https://github.com/xvoland/Extract/pull/20/

2022-02-24 15:06 UTC, druckdev commented
As you seem to still somewhat actively maintain this, I'd like to ask you to review this again.
The script does not work case insensitive even though it did once:
```bash
$ extract foo.ZIP
extract: 'foo.ZIP' - unknown archive method
```